version: '3'

services: 
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
    networks:
      - star-wars-network
    
  star-wars:
    build:
      dockerfile: ./Dockerfile
      context: .
    image: luyza/starwars
    container_name: starwarsAPI
    ports:
      - "8081:8081"
    environment: 
      - PORT=8081
      - MYSQL_CONTAINER=mysql
    networks:
      - star-wars-network
	depends_on: 
      - "mysql"
    
      
networks:
  star-wars-network:
    driver: bridge